### PR TITLE
refactor: improve code layering of ozhera-prometheus-agent module

### LINKED ISSUE #434: [Optimizing] Improve code layering of ozhera-prometheus-agent module
# Description
Some controller classes in the project currently use implementation classes of interfaces for dependency injection. While this method allows the project to function properly, it does not adhere to modern code layering practices and may lead to difficulties with future scalability and maintenance.

# Optimize
Separate interfaces from their implementation classes, ensuring standardized usage.

# Linked Module:
`ozhera-prometheus-agent`

### PR DESCRIPTION
**Pull request by psxjoy**
***Associate issue***:
fix #434 

***refactor module***:
ozhera-prometheus-agent

***Changes made***: 
1. Separated the service layer interfaces and their implementation classes in the `ozhera-prometheus-agent` module. 
2. Corrected spelling errors. 
3. Added comments to certain interfaces.

### CODE REVIEW

**Review by wodiwudi — APPROVED** [review]
+LGTM

**Review by sadadw1 — APPROVED** [review]
+LGTM

**Comment by psxjoy** [comment]
It looks like there's a problem with the `Lint Commit Messages` workflow, showing a lack of permission to run, which is preventing the code from merging automatically.Should I submit a new PR, or will you look into this workflow issue? 

看上去 `Lint Commit Messages` 这个 workflow有问题，提示没有权限运行，导致无法自动合并。我需要重新提交PR吗？或者你们会排查这个 workflow。 @wodiwudi @sadadw1

**Comment by wodiwudi** [comment]
Lint Commit workflow has been fixed and can now pass

**Pull request merged**
